### ISSUE TITLE
Hard Dependency on Redstone Arsenal

### ISSUE THREAD

**Issue by SirTyler** [MikeLydeamore/Ex-Astris#17]
Will crash unless Redstone Arsenal is also installed.
Log: http://pastebin.com/cq0snGgm
Build: http://ci.tterrag.com/job/Ex-Astris/8/

**Comment by SirTyler** [comment]
https://github.com/SirTyler/Ex-Astris/commit/f5eb94b6ba50d10401beb6b3b0feb85663ef5ba4

**Comment by SirTyler** [comment]
https://github.com/MikeLydeamore/Ex-Astris/pull/20

**Comment by ate0ate** [comment]
Looks like I am getting the same crash however I do have redstone arsenal installed...

crash log...
http://pastebin.com/E9D9wRmv
