### ISSUE TITLE
Auto sieve upgrades get pulled out

### ISSUE THREAD

**Issue by Staegrin** [MikeLydeamore/Ex-Astris#2]
When a hopper or any other method is used to extract the sieved items from the automatic sieve, the upgrades get pulled out as well. 

If this is intentional it can be worked around by using the extra utilities item filter (inverted).

**Comment by MikeLydeamore** [comment]
Fixed in 877bd1fea66f7aec054e1771b985dce15d3224b1. Thanks for the report.
