### ISSUE TITLE
Ex Astris added ores not going into Auto Hammer

### ISSUE THREAD

**Issue by Zero9o1o** [MikeLydeamore/Ex-Astris#22]
In version 1.15 the automatic hammerer won't process the following:
* Astral Silver Ore Gravel
* Atlarus Ore Gravel
* Carmot Ore Gravel
* Orchalcum Ore Gravel
* Oureclase Gravel Ore

**Comment by Staegrin** [comment]
It also doesn't process Cobalt and Ardite gravel/sand

**Comment by Zero9o1o** [comment]
* Meutoite Ore Gravel
* Infuscolium Ore Gravel
* Rubracium Ore Gravel
* Deep Iron Ore Gravel
* Adamantine Ore Gravel
* Prometheum Ore Gravel
* Mithril Ore Gravel

 They also don't get processed

**Comment by MikeLydeamore** [comment]
This is actually a bigger issue than I first thought when I looked into it. All Ex Astris registered ores are not going through the auto hammer currently.

**Comment by Staegrin** [comment]
Small addition. Silver, lead, tin and aluminium ore also don't work in the hammerer. gold, iron, osmium and  copper ore are hammered in the machine, thereby producing broken ores.

**Comment by MikeLydeamore** [comment]
Just as an update on this:
This can be fixed by moving to the Ex Nihilo Ore Creation System (and also fixes #5). I'll be moving to this, but it will break existing dusts in the world.

**Comment by HiRezDrifter** [comment]
Just to let you know as of version 1.16.26, there are 4 gravel ores that still do not work with the auto hammer.

Alduorite Ore Gravel
Ceruclase Ore Gravel
Kalenrite Ore Gravel
Vulcanite Ore Gravel

all others, gravel and sand versions, seem to be working though.

**Comment by MikeLydeamore** [comment]
I actually think this has been impacted in the latest versions. Note though that dusts are still going into the Auto Hammerer.

**Comment by HiRezDrifter** [comment]
I just updated both ex nihilo and ex astris and can confirm that this has been fixed
