### ISSUE TITLE
Crash with newer versions of Redstone Arsenal/CoFH Core...

### ISSUE THREAD

**Issue by ate0ate** [MikeLydeamore/Ex-Astris#23]
At first this looked the same as the hard dependency crash, but since I had Redstone Arsenal installed already and the crash persisted, it can't be caused by a dependency. After further testing I found that downgrading Redstone Arsenal and CoFH to older builds corrected the problem for now. It will become more of an issue after the newer CoFH builds become official releases.

Crash log using Ex Astris 1.16.8 and Redstone Arsenal 1.1.0RC1-35
http://pastebin.com/E9D9wRmv

Again, reverting back to Redstone Arsenal1.1.0RC1-31 prevents crash.

Thanks!

**Comment by ate0ate** [comment]
Nice! Thanks vey much for the fix. Any chance we can get a build with this implemented? Also, not sure if you're aware or not, but build 9 of ExAstris failed on tterrag's jenkins.

**Comment by MikeLydeamore** [comment]
No worries, thanks for pointing this out as I often don't keep up with mod updates as well as I maybe should.
Build 9 failed due to a missing dependency on the server, Build 10 contains the fix here: http://ci.tterrag.com/job/Ex-Astris/10/

**Comment by ate0ate** [comment]
Thanks! I always hate asking about updates as it comes across rather impatient. I appreciate the update greatly, and I look forward to seeing what you come up with next for Ex Astris:)

**Comment by ate0ate** [comment]
Well, here's where I eat my foot and restate that asking for updates is impatient. Looks as though the latest CoFH Core/Lib and Thermal Foundation are not compatible with any of the public builds of Thermal Expansion. Ex Astris build 10 will likely be useless until the time Thermal Expansion updates publicly since the versions of Thermal Foundation that it is compatible with cannot be used by us peasants... Sigh... Reverting back to Build 8  for now. Sorry about that.

**Comment by MikeLydeamore** [comment]
This is interesting, because I only used the public builds to get this working. I don't have any special access to any CoFH mods.

**Comment by ate0ate** [comment]
Yeah, Ex Astris works perfectly fine with the newer public CoFH mods, problem is the publicly available Thermal Expansion itself has issues with the the newer CoFH mods lol. Its been an ongoing issue now with their recent updates. Once Thermal Expansion itself is updated things should work properly again. Check out their github issues for more info...

Skyboy explains it best here...
https://github.com/CoFH/Feedback/issues/96

Dupes...
https://github.com/CoFH/Feedback/issues/98
https://github.com/CoFH/Feedback/issues/97
https://github.com/CoFH/Feedback/issues/91
https://github.com/CoFH/Feedback/issues/100
