### ISSUE TITLE
Smashing modifier nor respecting unbreakable status

### ISSUE THREAD

**Issue by Staegrin** [MikeLydeamore/Ex-Astris#24]
I was testing with the tinkers' construct pickaxe and hammer and discovered that even when the tool has reinforced X (the name in the description changes to unbreakable) it will still take damage when it is used. Normally the tool no longer takes damage.
![2015-02-11_23 49 31](https://cloud.githubusercontent.com/assets/8494635/6158232/c0d7aea0-b248-11e4-8e98-5dddcf6120f0.png)
While it is impossible in regular play to get reinforced up to level X it is 'easy' when playing with Iguana Tinker Tweaks the addon for tinkers' construct.

As such the smashing modifier isn't working well with the reinforced modifier. Just wanted to report this and let you know. Keep up the good work.

**Comment by MikeLydeamore** [comment]
Can you confirm the version of Ex Astris this is running on? I believe I fixed this a while back, but it hasn't yet made it to an official build.

**Comment by Staegrin** [comment]
Ex-Astris version 1.15

**Comment by MikeLydeamore** [comment]
Fixed in 1d5b499281a40d881c30ce6c8309566ea4ebaba3.
