### ISSUE TITLE
Crash with the latest Thermal Foundation

### ISSUE THREAD

**Issue by Neodark7** [MikeLydeamore/Ex-Astris#25]
http://pastebin.com/dV5t2Cnp

**Comment by ate0ate** [comment]
Yeah, I have the same crash myself. Looks like the public release of the thermal expansion update as well as the other CoFH mods had broken compatibility with ExAstris build 10...

**Comment by ate0ate** [comment]
I'm no expert by any means, but it looks like a pretty simple class renaming issue. Ex Astris is looking for thermalfoundation/entity/monster/EntityBlizz, which is now cofh/thermalfoundation/entity/monster/EntityBlizz.

**Comment by ate0ate** [comment]
Any chance we can get a build with this fix? This is the last mod I use in my private pack that needs to update before I can use the new Thermal Expansion builds:)

**Comment by Neodark7** [comment]
yeah same...

**Comment by MikeLydeamore** [comment]
Having an issue right now with the AE2 maven, but once that's back up and running I'll do a quick build.

**Comment by ate0ate** [comment]
Nice. Hope that things get sorted out soon. Thank you for your efforts good sir.

**Comment by MikeLydeamore** [comment]
You'll need:
Ex Nihilo: http://ci.tterrag.com/job/Ex-Nihilo/13/
Ex Astris: http://ci.tterrag.com/job/Ex-Astris/16/

Enjoy.

**Comment by ate0ate** [comment]
Thanks! Yeah, I noticed Ex Nihilo on the jenkins. Are you maintaining that as well now?
