### ISSUE TITLE
Thaumcraft Items are Broken

### ISSUE THREAD

**Issue by KamiKazeKenji** [MikeLydeamore/Ex-Astris#26]
Two bugs: 
  1. Thaumium hammer does not repair when enchanted with Repair.
* Reproduce: Enchant a Thaumium Hammer with Repair I or II (I used the Infusion Altar). Use it so it takes durability damage. Get a fully charged wand and wait. The hammer will not be repaired.
* Tested with Thaumcraft 4.2.3.3 and Ex Astris 1.15.
  2. Thaumic Doll does not summon a Pech.
* Reproduce: Get a Thaumic doll and a Thaumium Barrel. Fill the barrel with Witch Water. Right click the barrel with the doll. The barrel will accept the doll, but it won't summon a pech.
* Tested with Thaumcraft 4.2.3.3 and Ex Astris 1.15.

Both these features work just fine with Ex Astris 1.12.

**Comment by MikeLydeamore** [comment]
Fixed in 771db2d59dc9c8d2bfb4f34dce5c7831926a6011. My bad.
