### ISSUE TITLE
Crash with RF Crook and Hammer as well as Tinkers' Steelworks crash in build 1.16-10

### ISSUE THREAD

**Issue by AladinsjustSayian** [MikeLydeamore/Ex-Astris#27]
I'm getting this crash from using the most latest build and the newest public versions of CoFHcore, and the other TeamCoFH mods.

http://pastebin.com/5FKqYt4m - Crook crash
http://pastebin.com/pyxSUCdj - Hammer crash

Updated to this build to fix the conflict with Tinkers' Steelworks.
Ran this without Redstone Arsenal in the pack, but then I got a crash with Tinkers Steelworks

http://pastebin.com/vDYhLcHx

Sorry to throw all these crashes on you. I hope I'm helping rather than huring.

**Comment by MikeLydeamore** [comment]
To fix the third one, you'll need to update to a brand new Tinkers Steelworks from here http://tehnut.info/jenkins/job/TSteelworks/

The other two, fix on the way.

**Comment by MikeLydeamore** [comment]
Actually, the other two, I'm using the latest builds available on the CurseForge (not the Curse) from here:
http://minecraft.curseforge.com/mc-mods/70631-redstone-arsenal/files

You'll need the corresponding CoFH mods to boot. In those versions, there was a change which I had to conform to, but unfortunately this broke backwards compatibility. (See https://github.com/MikeLydeamore/Ex-Astris/commit/d25b45d52a54aaf826cc98d415caaa26c38e4f39)
