### ISSUE TITLE
Upgrading TiC Tools with Bone Crook Appears Not to Work

### ISSUE THREAD

**Issue by SilverKnightGG** [MikeLydeamore/Ex-Astris#3]
# Summary:
Could not get the **Crooked** modifier to apply to a TiC tool using the Tool Station or the Crafting Station next to it.
Not 100% positive this is actually a bug, but wanted to bring it to your attention just in case it is.  I am going to recheck all the literature I have access to and see if I overlooked something, but I think this is legit.

# Process:
* Placed tool into the upgrade slot(with the pickaxe icon in it).
* Tried placing **1 Bone Crook** into the adjacent slots(I know the top-left is usually the correct one for modifier recipes).
* Observed that no  'modified' tool was in the output slot(In fact, no tool at all at this point).
* Tried changing name of tool.  This resulted in a renamed version of the tool.
* Renamed version of the tool did not have a **Crooked** modifier in its tooltip text.
* Tested tool anyway, and found that my results were consistent with **not** using a **crook** to break leaves(The drop rate was normal for punching leaves).

Tested this on three different types of tools:  Pickaxe, Mattock and Hatchet.

**Comment by MikeLydeamore** [comment]
Thanks for the report. I need a little bit more information.
First off, the silly question, does your tool have a modifier available? If you're using Iguana Tweaks as well, then note that tools don't come with any modifiers.

I have been able to place a bone crook on a tool with an available modifier using the release version with no issue. Can you also please let me know what type of parts are on the pickaxe, mattock and hatchet, as well as if you have any other modifiers on the tools?

**Comment by SilverKnightGG** [comment]
That's not as silly a question as you think ;)  Indeed I am using Iguana Tweaks.  As much messing with modpacks as I've done, I'd not even realized that this one was in with my Skyblock 2 pack instance.  I had never played with it before either.  I will go ahead and close this issue, as it tests out to work once I get a modifier available on a tool.
