### ISSUE TITLE
Newest version of thermal expansion/redstone arsenal incompatibility

### ISSUE THREAD

**Issue by Staegrin** [MikeLydeamore/Ex-Astris#30]
So with the release of thermal dynamics all the other mods from the cofh team got updated as well.
Now the RF hammer introduced by Ex astris is no longer compatible and give a no class exception when starting minecraft. Thought I should notify you.

crash log:
http://pastebin.com/Q891wB29

**Comment by ate0ate** [comment]
I'm using Thermal Dynamics and all of the other CoFH updates with Ex Astris without any issue. See issue #25.  Are you using the version from the jenkins server? Try downloading Ex Nihilo and Ex Astris from tterrag's jenkins here...

http://ci.tterrag.com/

**Comment by Staegrin** [comment]
Yes, the latest versions from the Jenkins server seem to have fixed it.
