### ISSUE TITLE
Ex-Astris crashes on startup.

### ISSUE THREAD

**Issue by SprinkCal** [MikeLydeamore/Ex-Astris#32]
When I looked into the crashlog Ex-Astris was looking for the Blizz that was updated in the recent CoFH Thermal Foundation updates.
Please can you fix this so I can get back to my favourite modpacks.
Here is a Pastebin of thecrash.:  http://pastebin.com/BczWrDc3

**Comment by MikeLydeamore** [comment]
Fixed in https://github.com/MikeLydeamore/Ex-Astris/commit/771db2d59dc9c8d2bfb4f34dce5c7831926a6011

Please use the following builds:
Ex Nihilo: http://ci.tterrag.com/job/Ex-Nihilo/
Ex Astris: http://ci.tterrag.com/job/Ex-Astris/
