### ISSUE TITLE
Ex Astris Ores not going into pulverizer.

### ISSUE THREAD

**Issue by SprinkCal** [MikeLydeamore/Ex-Astris#36]
They just don't work.

**Comment by MikeLydeamore** [comment]
Do you mean Ex Nihilo ores or Ex Astris ores?

**Comment by SprinkCal** [comment]
Both.

**Comment by MikeLydeamore** [comment]
Was a problem in both. Has been fixed now, grab the two latest versions from http://ci.tterrag.com/
