### ISSUE TITLE
Crash with TSteelworks when Dust is not created for melting.

### ISSUE THREAD

**Issue by InkDragon** [MikeLydeamore/Ex-Astris#37]
http://paste.ee/p/UVo0p

Mods Installed:
Cookiecore - Required for tsteelworks
Ex Astris
Ex Nihilo
Mantel
Tconstruct
TSteelworks - https://github.com/Ephys/TinkersSteelworks

All versions are the latest available versions.

Crash happens at bootup, and can be 'fixed' by disabling dust smelting in the high oven.

**Comment by MikeLydeamore** [comment]
Please update to latest versions of Ex Astris (http://ci.tterrag.com/job/Ex-Astris/) and Ex Nihilo (http://ci.tterrag.com/job/Ex-Nihilo/) to fix this.

**Comment by InkDragon** [comment]
Still happening, even after updating to the latest ex Astris and Ex Nihilo builds from the links you provided.
http://paste.ee/p/Pjpby

Or should I post this on tsteelworks?

**Comment by MikeLydeamore** [comment]
Should be fixed now, was caused by nothing loading silver/copper etc and me not checking for it.

**Comment by InkDragon** [comment]
thank you <3
