### ISSUE TITLE
Crooked modifier not working with unbreakable.

### ISSUE THREAD

**Issue by SprinkCal** [MikeLydeamore/Ex-Astris#38]
Whenever I use a Tinkers' Construct tool with Unbreakable and Crooked it will use durability when used.
Looking through the other issues I found the same had been reported but for the Smashing modifier. It looks like only that was fixed. Please help.
![2015-02-28_15 14 13](https://cloud.githubusercontent.com/assets/11029201/6426296/80cc6ece-bf5c-11e4-900f-d49191de9bc4.png)
As you can see in the picture it is broken and has Reinforced X (Unbreaking).

**Comment by MikeLydeamore** [comment]
This was fixed alongside the hammering change. Can you please confirm your Ex Astris version as I am unable to reproduce this.

**Comment by SprinkCal** [comment]
Ex-Astris-MC1.7.10-1.16-18
It seems to only be unbreakable on wood but on items that can be 'crooked' (leaves) it will lose durability.

**Comment by SprinkCal** [comment]
Hello?

**Comment by MikeLydeamore** [comment]
I am 100% unable to reproduce this. I am using an unbreakable tool with crooked on it on leaves, and it's taking no durability damage.

**Comment by SprinkCal** [comment]
That's odd.
