### ISSUE TITLE
ExAstris/Block/TileEntity/TileEntityRotaryAlveary Issue

### ISSUE THREAD

**Issue by Herekar** [MikeLydeamore/Ex-Astris#45]
Juat had this issue come up after getting your new version to fix other issues with the rf hammer

http://pastebin.com/DtcjvK2f

**Comment by Herekar** [comment]
I tried swithing to the v 1.16-21 beta and was able to get past this error so whatever changes you made you are on the right track

**Comment by MikeLydeamore** [comment]
Is this still an issue with the Jenkins version?

**Comment by Herekar** [comment]
before i tried the 1.16-21 version i could even load completely but now i can and have done so multiple times so i would say as far as this goes its all good with what ever changes you made between versions.  I am still in the process of in game testing so if any thing else comes up i will let you know.
