### ISSUE TITLE
Auto Hammer Crash with Sand

### ISSUE THREAD

**Issue by whythisname** [MikeLydeamore/Ex-Astris#46]
When I try to put sand in the Auto Hammer (via the UI) the game crashes to desktop. I'm running the latest build of Resonant Rise with version 1.15 of Ex Astris (which I updated myself because the version of Ex Astris that is in RR causes a crash on start up). This is the crashlog:

http://paste.atlauncher.com/view/6b8fcfcf

I haven't tried putting anything else in yet. If this is related to #22 feel free to ignore this.

**Comment by MikeLydeamore** [comment]
You'll also need to update Ex Nihilo (from the CurseForge page) for this. If you're still using 1.15, it may be worth updating Ex Astris from the CurseForge page as well.

**Comment by whythisname** [comment]
I had made a mistake in my bug report, I had already updated Ex Astris to 1.16-21. But updating Ex Nihilo fixed the issue so it's all good now :)
