### ISSUE TITLE
Metallurgy Support: Missing Zinc grave/dust/sand, possibly silver and platinum as well

### ISSUE THREAD

**Issue by Monstrel** [MikeLydeamore/Ex-Astris#47]
Dusts for Metallurgy's precious metals (zinc, platinum, silver) are not created by Ex Astris.  Ex Nihilo produces these dusts, sands and gravels for platinum and silver if Thermal Expansion is installed so it makes sense that they were overlooked, but zinc is completely absent regardless.

**Comment by MikeLydeamore** [comment]
Using just Metallurgy + Ex Nihilo + Ex Astris, both Platinum and Silver generate for me (http://puu.sh/gwUSD/13a5a7254f.jpg). I'll get onto adding Zinc shortly.
