### ISSUE TITLE
Crash with Steve's Factory Manager

### ISSUE THREAD

**Issue by Nathan1852** [MikeLydeamore/Ex-Astris#50]
When trying to Automate the hammer with the Factory Manager, Minecraft Crashes with this Error:

http://hastebin.com/xukugaxiju.coffee

**Comment by MikeLydeamore** [comment]
You need to update Ex Nihilo to the latest version.

**Comment by Nathan1852** [comment]
I have Ex Nihilo 1.37, which is the latest version I can find

**Comment by MikeLydeamore** [comment]
Try here: http://www.curse.com/mc-mods/minecraft/221696-ex-nihilo#t1:other-downloads

**Comment by Nathan1852** [comment]
It is working with the new version, thank you
