### ISSUE TITLE
String and crooks

### ISSUE THREAD

**Issue by jadedcat** [MikeLydeamore/Ex-Astris#51]
Not sure if its Ex Astris or Ex Nihilo or something else but after the last update to AgSkies 2, crooks don't harvest string from infested leaves, breaking the leaves with your hands drops string. 

http://minecraft.curseforge.com/forums/jadeds-packs/agrarian-skies-2/773-agskies-2-alpha-bugs?comment=149

http://minecraft.curseforge.com/forums/jadeds-packs/agrarian-skies-2/773-agskies-2-alpha-bugs?comment=153

**Comment by MikeLydeamore** [comment]
Oh dear...

This was an Ex Nihilo issue, and should be fixed in v1.38-21.

Feel free to re-open if issue persists.
