### ISSUE TITLE
Auto hammer/sieve without TE/EIO

### ISSUE THREAD

**Issue by CrazyNagaraj** [MikeLydeamore/Ex-Astris#53]
When no Thermal Expansion nor EnderIO presents, the auto hammer/sieves are not present, even in creative menu. Why?
These auto blocks only requires the CofhCore right?. As per crafting recipes, We can use own specified recipes(u know, any of Buildcraft gears&chips, Forestry circuits&gears, Railcraft steel&gears or even vanilla items).

Please make sure Auto hammer/sieve are loaded even when no TE/EIO present, So we can use them in buildcraft/Forestry/Railcraft based skyblock modpacks. Whats point having upgrades available, when auto hammer/sieve are not available.

**Comment by m31317015** [comment]
Well it needs Thermal Foundation, too, since the recipe is using those thermal expansion metals.

**Comment by CrazyNagaraj** [comment]
@m31317015 That way i am asking for, Only recipes requires thermal foundation, Not using any materials inside nor any code ( try with EnderIO without thermal foundation+expansion. Recipes uses EIO materials ).

These blocks only requires COFHCore. We can change receipes with MineTweaker, Not a problem at all.

If it is implemeted, I can use other Materials (I am using Buildcraft chips/gears currently) to define recipes.

That way these blocks are useful in modpacks without TE/EIO (Besides, Automation of ExN sieve not possible without Autonomous Activator from TE, Thats makes sieving a great problem in Buildcraft based modpack). I hope you got my point... :)

**Comment by tterrag1098** [comment]
BTW @MikeLydeamore I was wrong about Loader.isModLoaded checking for APIs, it does not (even cpw thought it did, we had an hour-long investigation into why it does not). You can use ModAPIManager.INSTANCE.hasAPI() to check for CoFHAPI|energy

**Comment by m31317015** [comment]
If I'm not wrong, this mod detects for not the RF api, but the mod or ore dictionary ingot... So either you change the recipe with MineTweaker or not, it's still searching for those ingots...

**Comment by tterrag1098** [comment]
@m31317015 We intend to change it to check for the RF API container, as that is the most flexible way to do it. A vanilla-based recipe will have to be devised, but that is a small issue.
