### ISSUE TITLE
Automatic hammer eats dusts.

### ISSUE THREAD

**Issue by NJM1564** [MikeLydeamore/Ex-Astris#55]
Most things can't get inserted into the the auto hammer but dusts can and do.
It becomes a problem with some automatic set ups. I have no idea how much materials I lost before I figures out what was wrong.
Please fix at your earliest available convenience.
________________________________________________________________ Love and monkeys. 
______________________________________________________________________Signed: Me

**Comment by MikeLydeamore** [comment]
It's my understanding that all Ex Nihilo added gravel ores, sands and dusts work fine, but the implementation on the Ex Astris dusts are causing an issue. This is a work in progress as I'm moving everything over to the Ex Nihilo system.
