### ISSUE TITLE
Crash when loading an existing world

### ISSUE THREAD

**Issue by bochen415** [MikeLydeamore/Ex-Astris#57]
As title

happened when loading an existing world on a server after updating ExAstris and ExNihilo
Ex-Nihilo-1.38-26.jar 
Ex-Astris-MC1.7.10-1.16-29.jar 
and other mods
Forge 1342

Crash log http://paste.ubuntu.com/10755172/

Reverting to:
Ex-Astris-MC1.7.10-1.16-28.jar
Ex-Nihilo-1.38-25.jar
fixed the issue.

**Comment by MikeLydeamore** [comment]
Interesting, can you try picking up the sieve and updating, then replacing it?

**Comment by bochen415** [comment]
Interesting indeed.

I loaded the world with the previous versions:
Ex-Astris-MC1.7.10-1.16-28.jar
Ex-Nihilo-1.38-25.jar

I removed all 6 sieves from the world and I've put them into a chest (item form).

I updated both mods (client and server) to:
Ex-Nihilo-1.38-26.jar
Ex-Astris-MC1.7.10-1.16-29.jar 

I started the server... OK.
Loaded the client... OK
Server finished loading the world...OK
Client connected... OK
Placed one sieve in-world...OK (started sifting) 
Placed the other... OK
Placed the third... client disconnected ("server closed" message)... not OK

crash log from server: http://paste.ubuntu.com/10756189/

The sieve was connected with enderio item conduits, one with insert mode (sending in gravel) and the other with extract mode (redstone control disabled to actively extract items). 
The power was sent from the bottom with enderio energy conduits (that was the only sieve that had power connected from the bottom in my setup).
Item conduits were connected to the sides.
I had some upgrades planned but never made that far. They weren't used in the test.

**Comment by MikeLydeamore** [comment]
Just to confirm, there was only one sieve that was processing when the server crashed?

**Comment by MikeLydeamore** [comment]
Never mind, I'm able to reproduce this. I'll work on it.

**Comment by bochen415** [comment]
Glad you could reproduce it. My timezone setting insisted on me getting some sleep.
Can you translate the commit to English please?

**Comment by MikeLydeamore** [comment]
Most of the work is actually over in Ex Nihilo. The commit 0600dbd871d791be1f36a9343b1a1f36b3d41112 is a failsafe if for some reason that handling doesn't work.

What was really going on is that I was keeping track of the ID of an item, which is not safe, and so strange things were happening in regards to what was registered for sieving.
