### ISSUE TITLE
Automatic Sieve does not give output & crash the game

### ISSUE THREAD

**Issue by m31317015** [MikeLydeamore/Ex-Astris#58]
The Automatic Sieve seems working pretty smooth, but when it's done, it crashes the world and no output were given.

Detail : http://pastebin.com/smF3SgPq

Notice that when I update to build 31 the problem still exist.

**Comment by MikeLydeamore** [comment]
Please update your Ex Nihilo version.

**Comment by m31317015** [comment]
Oh thx
