### ISSUE TITLE
Auto hammer v1.16-31

### ISSUE THREAD

**Issue by Chefbarbie** [MikeLydeamore/Ex-Astris#63]
Any time I try to manually add anything to the autohammer (materials or upgrades) I get a crash. 
This also happens when items are piped in.

Open Eye: http://openeye.openmods.info/crashes/500beaf04466df17de9e339a0fd10e8f
Crash log: http://pastebin.com/hKaiWNeq

**Comment by MikeLydeamore** [comment]
Update Ex Nihilo,

**Comment by Chefbarbie** [comment]
Is there a version higher than 1.37?

**Comment by MikeLydeamore** [comment]
Yes http://minecraft.curseforge.com/mc-mods/221696-ex-nihilo/files

**Comment by Chefbarbie** [comment]
wowfastthanks

**Comment by Chefbarbie** [comment]
Since this hasn't been closed yet... Are you maintaining exnihilo now? If so, updating seriously broke modtweaker scripts. My pam's fish to compost doesn't work and my nether quartz dust and fluix dusts from sifting don't work, even though they show up in NEI.

**Comment by MikeLydeamore** [comment]
I am maintaining Ex Nihilo.
ModTweaker was broken when I overhauled a lot of the backend to make life a little saner (mainly for ModTweaker actually!)

You can manually add entries to be composted in the ex nihilo config, by either oredict value or modid:blockname format. At this point, you cannot manually add sifting items, although this is something I can look to implement.
Note the items will still show up in NEI (the old storage methods still exist to avoid crashes)

**Comment by Entiz** [comment]
I have got a similar error report
http://openeye.openmods.info/crashes/78643b2e199ee838b5b6f307139b8f36
http://pastebin.com/T5vwhqq4
i use the Ex-Nihilo-1.38-31
