### ISSUE TITLE
Crash with Sieve and Hammer

### ISSUE THREAD

**Issue by Entiz** [MikeLydeamore/Ex-Astris#64]
I've got two errors that Crash Minecraft i use the latest Forge10.13.3.1378, Ex-Nihilo-1.37, ExAstris 1.16-31
First the Error with the Sieve it Crashes after the Sieve is finished the crash report Say its a Server but i play on Singelplayer
http://pastebin.com/ByjKTx1X
http://openeye.openmods.info/crashes/5fc4a41fbf6cdf6656b9ee2b9d3509ec

The Second Error is with auto Hammer
it crash right after i put an item in the GUI
http://pastebin.com/A8E07JNg
http://openeye.openmods.info/crashes/78643b2e199ee838b5b6f307139b8f36

I use many differend mods i hope the problem is fixabel

**Comment by MikeLydeamore** [comment]
Update Ex Nihilo to fix both of these.

**Comment by Entiz** [comment]
Ok now it works, seems i clickt on the wrong button at Curse so i download the recommended and not the latest.
