### ISSUE TITLE
Autosieve doesn't respect the dirt droplist

### ISSUE THREAD

**Issue by Timeslice42** [MikeLydeamore/Ex-Astris#68]
When using minetweaker (thanks for that, BTW) to change the drops for dirt, the autosieve doesn't respect that drop list. Dirt has the correct drops in a regular sieve, and gravel, sand, and dust have the correct drops in the autosieve, so I'm not sure what's going on. Either way, you're the guy to tell about it.

**Comment by MikeLydeamore** [comment]
I'm not quite sure what you mean. Are you getting things that are removed, not getting things that are added, or both? Both the AutoSieve and the normal sieve use the same code, but I will try and investigate.

**Comment by Timeslice42** [comment]
Both. I'm getting the correct drops from the sieve, but not the autosieve. And I was mistaken, gravel, sand, and dust also have the same problem. It's almost like the autosieve is caching the drops before minetweaker can change them.

**Comment by Timeslice42** [comment]
Closing this as this fork is basically dead.

**Comment by MikeLydeamore** [comment]
https://github.com/Ex-Astris-Rebirth/Ex-Astris-Rebirth

**Comment by Timeslice42** [comment]
That's my point.
