### ISSUE TITLE
Hammered tools crashing game

### ISSUE THREAD

**Issue by Tedyhere** [MikeLydeamore/Ex-Astris#69]
Tools with the hammer modifies work fine on things that can be broken down into dust but if i mine anything else with it it crashes.

http://pastebin.com/djD9AizH

I will update to latest version, I am one behind on Davy Jones Locker modpack at the moment.

**Comment by LordPMac** [comment]
I'm Playing Agrarian Skies 2  and the game crashed on me when using Stone hammer on dust.

as well I upgrade a TiCon Pickaxe with a Diamond Hammer and when I used the pick on Cobble, ore Sand and ore Gravel, the game also crashed

http://pastebin.com/ivSp5LFu
http://pastebin.com/QkXjGC7a

**Comment by tterrag1098** [comment]
This was fixed here https://github.com/MikeLydeamore/Ex-Astris/commit/b8e7f51a053c3637995019b0b3ff61340836c5a4#diff-6a0ae6adb8d627aee970b4b3f402e81cL53

So @Tedyhere I'd recommend that new version ;)
