### ISSUE TITLE
Textures broken when mod removed

### ISSUE THREAD

**Issue by ecoay** [MikeLydeamore/Ex-Astris#71]
I removed enderio from modpack and it bjorked the textures for automatic hammer and automatic sieve. I wouldn't think enderio would be a requirement?

**Comment by MikeLydeamore** [comment]
It's not, can you post a screenshot please?

**Comment by ecoay** [comment]
http://snag.gy/ujJzA.jpg

**Comment by MikeLydeamore** [comment]
Paging @tterrag1098
