### ISSUE TITLE
Autosieve Crash [Solved] (Off Topic Question as well)

### ISSUE THREAD

**Issue by Drakoflame** [MikeLydeamore/Ex-Astris#75]
I got a crash when I tried to use the auto sieve, details here:
http://pastebin.com/eD2cwn6x

(c/p'd that^^ from over on the Curse page, stupidly posted there when I should have came here)
Anyway, I was wondering if your working on this/have noticed this/can help me with this, because I spent allot of time working on getting some invar and electrum only to have my game crash when I finally put some dust into my sieve... I DO have the EN sieve automation enabled, I'd just like to not need to make a vacuum hopper to grab the stuff as it explodes, Need to save up my ender pearls early so I can make some Enderium! (that and I don't have a mobfarm that is enderman friendly XD)

**Comment by MikeLydeamore** [comment]
Easy fix: Update Ex Nihilo.

**Comment by LoveHoly** [comment]
http://minecraft.curseforge.com/mc-mods/221696-ex-nihilo/files

1.38 version download

**Comment by Drakoflame** [comment]
OOOOOOOHH! Thank you! I didn't even think of that XD Thanks guys! Keep up the amazing work!
Um... biiiit of an off topic question... but, is it something done with MineTweeker, or is it something else in EN that allows me to throw gravel/sand into a Thermal Expansion Pulverizer to get gravel>sand>dust? if I can then that would be amazing, otherwise I'll just be using my pulberizer to get flint for my TC tools

**Comment by MikeLydeamore** [comment]
That is inside Ex Nihilo.
