### ISSUE TITLE
[Bug/Suggestion] Blazes not spawning

### ISSUE THREAD

**Issue by Timeslice42** [MikeLydeamore/Ex-Astris#76]
If you attempt to spawn a blaze, using an angry doll, in a room that's too small (such as 5x5x3) then the blaze can sometimes fail to spawn, but the doll and lava still get used up. Could you either make several attempts to spawn, or not consume the materials if the spawn fails?

**Comment by Timeslice42** [comment]
Dangit, this is an Ex Nihilo issue, not Ex Astris. Do you want me to close this and open one in the ex nihilo repository?

**Comment by MikeLydeamore** [comment]
Would probably be a good idea, otherwise I'll forget.

**Comment by Timeslice42** [comment]
Done
