### ISSUE TITLE
Let them eat cake! aka Ender Cake issue

### ISSUE THREAD

**Issue by Timeslice42** [MikeLydeamore/Ex-Astris#84]
You can only eat ender cake if you're hungry. This is a problem in a dimension where the player has the saturation effect... Since the cake (shouldn't) actually restore hunger when eaten, can it be changed to be always edible?

**Comment by MikeLydeamore** [comment]
This was fixed 3 months ago ad866534fff49087fadd44835e31d356c2ab3458
