### ISSUE TITLE
Auto-Hammerer causes game to crash

### ISSUE THREAD

**Issue by FuuNoKamiOka** [MikeLydeamore/Ex-Astris#85]
I have a modified version of the Direwolf20 pack where I added Ex Nihilo and EX Astris. I've had no problems with it since adding those mods, but I just made an auto-hammerer and as soon as I put cobble into the slot of the machine my client crashes. No idea why, but here is a pastebin of the crash report. Hopefully it can be fixed soon. I will check if the same thing happens with the sieve, too.

Report: http://pastebin.com/EPmxQwnG

**Comment by tterrag1098** [comment]
You have mismatched versions, make sure you are up to date on both Ex
nihilo and ex astris

**Comment by FuuNoKamiOka** [comment]
That was indeed the problem. Thank you for that. lol
