### ISSUE TITLE
Auto-Hammerer causes fatal error

### ISSUE THREAD

**Issue by FuuNoKamiOka** [MikeLydeamore/Ex-Astris#86]
I have been using the auto-hammerer and it's been working fine until today. I put in some copper ore and it chewed it up alright. I also put some aluminum ore in it and that's when the problems started. I broke the hopper that was feeding the ores in, but when I tried to access the auto-hammerer my game crashed (?). It goes to a screen that says: 

"Connection Lost
A fatal error has occurred, this connection is terminated."

It has the "Back to the title screen" button below it, but when I click it, it takes me to the multiplayer screen where you'd pick a server to play on.

I have no idea what is happening and it's frustrating me. I have Thermal Foundation, Expansion and Dynamics updated. I also have Tinkers construct updated as well. Someone help me figure out this problem.

**Comment by MikeLydeamore** [comment]
Can you please confirm your Ex Astris and Ex Nihilo versions?

**Comment by FuuNoKamiOka** [comment]
I updated to the latest version of each. I'm still not exactly sure what the problem was, but I think it was something with NEI. Every time I would open an inventory the crash would happen. I don't think it was on this mod's end. I apologize for posting wrong information.
