### ISSUE TITLE
Attemting to apply armor modifier causes crash

### ISSUE THREAD

**Issue by Shados** [MikeLydeamore/Ex-Astris#9]
Attempting to apply one of the new TC armor modifiers causes a client-side crash -- the ModCrooked and ModHammered canModify() methods are the issue, as they blindly cast the passed ItemStack to a ToolCore without confirming it is one first.

**Comment by MikeLydeamore** [comment]
I'm unable to craft the Exo-Suit from Tinkers to test this. How did you manage to get hold of it?

**Comment by Shados** [comment]
You don't need an 'Exo-Suit', armor modifiers are applied to any of the Traveler's gear.
